default['dir'] = '/chef'
default['packageSource'] = 'https://packages.chef.io/files/stable/chef-server/14.4.4/el/7/chef-server-core-14.4.4-1.el7.x86_64.rpm'
default['packageName'] = 'chef-server-core-14.4.4-1.el7.x86_64.rpm'
default['userName'] = 'admin'
default['userMail'] = 'my@email.com'
default['orgName'] = 'someorg'
default['orgFullName'] = 'voprosovNet'